export const siteMetadata = {
  siteName: 'ZM6 Digital',
  siteTagline: 'Marketing e tecnologia para acelerar vendas',
  description:
    'ZM6 Digital é uma agência especializada em marketing, tecnologia e automação que cria sites, sistemas e estratégias para gerar resultados reais.',
  siteUrl: 'https://zm6digital.com.br',
  defaultImage: 'https://zm6digital.com.br/og-image.jpg',
  keywords: [
    'zm6 digital',
    'agência zm6',
    'agência de marketing digital',
    'desenvolvimento web profissional',
    'automação de vendas para empresas',
    'sites profissionais e-commerce',
    'marketing digital de performance',
    'agência de marketing [sua cidade]',
    'desenvolvimento de sites wordpress',
    'serviços de automação de marketing',
    'criação de sites profissionais preço',
    'consultoria de marketing digital',
    'zm6 marketing digital',
    'melhores agências de marketing',
    'desenvolvedor web freelancer',
    'implementação de automação de vendas',
    'sites para pequenas empresas',
    'estratégias de marketing digital 2025',
    'agência de marketing perto de mim',
    'desenvolvimento de landing pages',
    'automação de funil de vendas',
    'plataforma para sites profissionais',
    'otimização de sites seo',
    'zm6 digital contato',
    'marketing digital para iniciantes',
    'desenvolvimento de aplicativos web',
    'ferramentas de automação de marketing',
    'sites responsivos para celular',
    'como posicionar site no google',
    'agência de seo e tráfego pago',
    'zm6 digital portfólio',
    'gestão de redes sociais para empresas',
    'web design e desenvolvimento',
    'crm e automação de vendas',
    'sites empresariais modernos',
    'inbound marketing para pme',
    'agência de branding e marketing',
    'desenvolvimento web com python',
    'automação de whatsapp para vendas',
    'manutenção de sites profissionais',
    'análise de dados marketing',
    'agência de marketing para startups',
    'desenvolvimento de sistemas web',
    'automação de email marketing',
    'sites profissionais com blog',
    'treinamento em marketing digital',
    'agência de growth hacking',
    'zm6 sistemas',
    'desenvolvimento de e-commerce shopify',
    'automação de leads'
  ],
  social: {
    instagram: 'https://instagram.com/zm6digital',
    facebook: 'https://facebook.com/zm6digital',
    whatsapp: 'https://wa.me/5511951505824',
  },
  contact: {
    phone: '+55 11 95150-5824',
    email: 'contato@zm6digital.com',
    address: 'São Paulo, SP - Brasil',
  },
};

export type StructuredData = Record<string, unknown>;

